### ISSUE TITLE
[Feature Request] weighted edges

### ISSUE THREAD

**Issue by zachmayer** [DAMA-UPC/SCD#2]
I have a graph where each edge also has a weight associated with it. SCD works pretty well when I remove the edge weights, but I was wondering if there'd be a straightforward way to incorporate that information into the algorithm.

**Comment by ArnauPrat** [comment]
Hi @zachmayer, thanks for your interest on the algorithm
Theoretically, adding the concept of weights into to the metric the algorithms uses to find the communities is straightforward. The problem is that the procedure the algorithm uses to optimize the metric uses a set of heuristics to speed up the overall proceess, whcih have not been thought to take the weights into account. Not using the heuristics increases the time complexity of the algorithm, and finding new heuristics to include weights is not something easy. So unfortunately, there is not an straightforward way right now to include weights into the equation.

Regards,

Arnau

**Comment by zachmayer** [comment]
@ArnauPrat I assumed if it was straightforward, you would have done it, but figured it couldn't hurt to ask.

Fyi, [I've also asked the people over at igraph to add SCD to their library](https://github.com/igraph/igraph/issues/829).  If you're not familiar with igraph, it's a really popular graph analytics package written in C, with very well-designed interfaces to R and python. If you are familiar with igraph, I think SCD would make an excellent addition to the library, if you feel like contributing.

Again, thanks for writing this implementation.  It's already been immensely useful to me.
